apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME-svc
spec:
  type: NodePort
  selector:
    app: $SERVICE_NAME
  ports:
    - protocol: TCP
      port: $SERVICE_PORT
      targetPort: $SERVICE_PORT
