apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
  - name: my-app
    image: curlimages/curl
    command: ["sleep", "3600"]
  nodeSelector:
    kubernetes.io/hostname: k8s-worker-1
