apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  clusterIP: {{ .Values.service.clusterIP | default "None" }}
  ports:
    - name: http
      port: 6901
      protocol: TCP
      targetPort: 6901
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-loadbalancer
#   labels:
#     app: {{ .Release.Name }}
# spec:
#   allocateLoadBalancerNodePorts: true
#   loadBalancerIP: {{ .Values.service.loadBalancerIP | default "None" }}
#   externalTrafficPolicy: Cluster
#   internalTrafficPolicy: Cluster
#   ports:
#     - name: http
#       nodePort: {{ .Values.service.nodePort }}
#       port: 6901
#       protocol: TCP
#       targetPort: 6901
#   selector:
#     app: {{ .Release.Name }}
#   type: LoadBalancer
